name: Test and Build SPlayer

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fix node-gyp for Windows
      run: |
        npm i -g node-gyp@6.0.1
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      if: matrix.os == 'windows-latest'
    - name: Install dependencies
      run: |
        yarn
        node scripts/check-electron-version.js
    - name: Test
      run: |
        yarn run lint
        yarn test
      if: matrix.os == 'macOS-latest'
    - name: Build
      run: yarn build
